//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 06:42:22 PM IST 
//


package com.netPoint.applications.site.service.soap.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.netPoint.applications.site.service.soap.model.Order;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.blog.javaguys.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName QOrder = new QName("http://com.netpoint/schemas", "QOrder");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.blog.javaguys.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public Order createCreateHeader() {
        return new Order();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Client }{@code >}}
     * 
     */
  /*  @XmlElementDecl(namespace = "http://localhost:8080/netpoint/", name = "Client")
    public JAXBElement<Order> createClient(Customer value) {
        return new JAXBElement<Order>(_Orders_QNAME, Order.class, null, value);
    }*/
    /**4
     * Create an instance of {@link JAXBElement }{@code <}{@link Client }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.netPoint.fr/schemas", name = "Order")
    public JAXBElement<Order> createOrders(Order value) {
        return new JAXBElement<Order>(QOrder, Order.class, null, value);
    }
    @XmlElementDecl(namespace = "http://com.netPoint.fr/schemas", name = "Customer")
    public JAXBElement<Customer> createCustomer(Customer value) {
        return new JAXBElement<Customer>(QOrder, Customer.class, null, value);
    }
    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

   
}
