//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 06:42:22 PM IST 
//


package com.netPoint.applications.site.service.soap.endpoint.GetOrders;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.netPoint.applications.site.service.soap.model.Customer;
import com.netPoint.applications.site.service.soap.model.Order;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "Order",
    "Customer"
})
@XmlRootElement(name = "GetOrdersResponse")
public class GetOrdersResponse {
	@XmlElement(required = true)
	protected Customer Customer;
	@XmlElement(required = true) 
    protected List<Order> Order;

	/**
	 * @return the orders
	 */
	public List<Order> getOrders() {
		return Order;
	}
	public void setOrders(List<Order> orders) {
		this.Order = orders;
	}
	/**
	 * @return the customer
	 */
	public Customer getCustomer() {
		return Customer;
	}




	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.Customer = customer;
	}

}
